FROM rust:1.80 AS builder

WORKDIR /meu_projeto

COPY . .

RUN cargo build --release

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /meu_projeto/target/release/linhas_de_execucao .

CMD ["./linhas_de_execucao"]